export const MAKE_EN = {
  "אאודי": "Audi",
  "אבארט": "Abarth",
  "אווטאר": "Avatr",
  "אוטוביאנקי": "Autobianchi",
  "אומודה": "Omoda",
  "אופל": "Opel",
  "אורה": "Ora",
  "אי.וי איזי ": "EV Easy",
  "איוויס": "Aiways",
  "איווקו": "Iveco",
  "איי אם": "IM",
  "אינאוס": "Ineos",
  "אינפיניטי": "Infiniti",
  "איסוזו": "Isuzu",
  "אל.אי.וי.סי": "LEVC",
  "אל.טי.איי": "LTI",
  "אלפא רומיאו": "Alfa Romeo",
  "אלפין": "Alpine",
  "אם ג'י": "MG",
  "אס דאבל יו אמ": "SWM",
  "אסטון מרטין": "Aston Martin",
  "אקורה": "Acura",
  "אקס אי וי": "XEV",
  "אקסיד": "Exeed",
  "אקספנג": "Xpeng",
  "ארקפוקס": "Arcfox",
  "ב מ וו": "BMW",
  "באייק": "BAIC",
  "בי.איי.דאבליו": "BAW",
  "בי.ווי.די": "BYD",
  "ביואיק": "Buick",
  "בנטלי": "Bentley",
  "ג'אקו": "Jaecoo",
  "ג'י.איי.סי": "GAC",
  "ג'י.אם.סי": "GMC",
  "ג'יפ": "Jeep",
  "ג'נסיס": "Genesis",
  "גופיל": "Goupil",
  "גיאיוואן": "Jiayuan",
  "גרייט וול": "Great Wall",
  "ג׳יי.איי.סי": "JAC",
  "ג׳ילי": "Geely",
  "דאבל יו אם מוטורס": "WM Motor",
  "דאיון": "Dayun",
  "דאצ'יה": "Dacia",
  "דודג'": "Dodge",
  "דונגפנג": "Dongfeng",
  "די.אס": "DS",
  "דייהו": "Daewoo",
  "דייהטסו": "Daihatsu",
  "דיפאל": "Deepal",
  "האמר": "Hummer",
  "הונגצ'י": "Hongqi",
  "הונדה": "Honda",
  "וויה": "Voyah",
  "וולוו": "Volvo",
  "ויי": "WEY",
  "זיקר": "Zeekr",
  "טאטא": "Tata",
  "טויוטה": "Toyota",
  "טסלה": "Tesla",
  "יגואר": "Jaguar",
  "יודו": "Yudo",
  "יונדאי": "Hyundai",
  "לאדה": "Lada",
  "לוטוס": "Lotus",
  "לינק אנד קו": "Lynk & Co",
  "לינקולן": "Lincoln",
  "לינקסיס": "Lynxys",
  "ליפמוטור": "Leapmotor",
  "למבורגיני": "Lamborghini",
  "לנד רובר": "Land Rover",
  "לנצ'יה": "Lancia",
  "לקסוס": "Lexus",
  "מאזדה": "Mazda",
  "מאן": "MAN",
  "מורגן": "Morgan",
  "מזראטי": "Maserati",
  "מיני": "Mini",
  "מיצובישי": "Mitsubishi",
  "מקלארן": "McLaren",
  "מקסוס": "Maxus",
  "מרצדס-בנץ": "Mercedes-Benz",
  "נטע": "Neta",
  "ניאו": "NIO",
  "ניסאן": "Nissan",
  "ננג'ינג": "Nanjing",
  "סאאב": "Saab",
  "סאנגיונג": "SsangYong",
  "סאנשיין": "Sunshine",
  "סובארו": "Subaru",
  "סוזוקי": "Suzuki",
  "סיאט": "Seat",
  "סיטרואן": "Citroen",
  "סמארט": "Smart",
  "סנטרו": "Cenntro",
  "סקודה": "Skoda",
  "סקייוול": "Skywell",
  "סרס": "Seres",
  "פאריזון": "Farizon",
  "פוטון": "Foton",
  "פולסטאר": "Polestar",
  "פולקסווגן": "Volkswagen",
  "פונטיאק": "Pontiac",
  "פורד": "Ford",
  "פורשה": "Porsche",
  "פורתינג": "Forthing",
  "פיאג'ו": "Piaggio",
  "פיאט": "Fiat",
  "פיג'ו": "Peugeot",
  "פרארי": "Ferrari",
  "צ׳רי": "Chery",
  "קאדילק": "Cadillac",
  "קארמה": "Karma",
  "קופרה": "Cupra",
  "קיה": "Kia",
  "קיי גי אם ": "KGM",
  "קרייזלר": "Chrysler",
  "ראם": "Ram",
  "רובר": "Rover",
  "רולס רויס": "Rolls-Royce",
  "ריהיי": "RuiChi",
  "רנו": "Renault",
  "שברולט": "Chevrolet",
  "תעשיות רכב": "AIL",
}

export const MODEL_EN = {
  "124 ספיידר": "124 Spider",
  "200 SX": "200SX",
  "575M מרנלו": "575M Maranello",
  "812 סופרפאסט": "812 Superfast",
  "911 קאררה": "911 Carrera",
  "AMG GT 4 דל' קופה": "AMG GT 4-Door Coupe",
  "B-series": "B-Series",
  "B4/לגאסי": "B4/Legacy",
  "C אליזה": "C-Elysee",
  "C קרוסר": "C-Crosser",
  "C-זירו": "C-Zero",
  "C3 איירקרוס": "C3 Aircross",
  "C4 פיקאסו": "C4 Picasso",
  "C4x": "C4 X",
  "C5 איירקרוס": "C5 Aircross",
  "EQ פורטו": "EQ Fortwo",
  "F8 טריבוטו": "F8 Tributo",
  "F8 ספיידר": "F8 Spider",
  "FJ קרוזר": "FJ Cruiser",
  "GLC קופה": "GLC Coupe",
  "GTS 296": "296 GTS",
  "I20 קרוס": "i20 Cross",
  "I20N": "i20N",
  "I30N": "i30N",
  "I35": "i35",
  "ID.Buzz": "ID. Buzz",
  "KO1": "K01",
  "KO2": "K02",
  "KO5": "K05",
  "MHERO 1": "M-Hero 1",
  "MR 2": "MR2",
  "PT קרוזר": "PT Cruiser",
  "S-מקס": "S-Max",
  "T-קרוס": "T-Cross",
  "T-רוק": "T-Roc",
  "X-class": "X-Class",
  "אאוטבק": "Outback",
  "אאוטלנדר": "Outlander",
  "אבאו": "Aveo",
  "אבולטיס/אסנט": "Evoltis/Ascent",
  "אביאטור": "Aviator",
  "אדג'": "Edge",
  "אדם": "Adam",
  "אודיסיי": "Odyssey",
  "אוולון": "Avalon",
  "אוונג'ר": "Avenger",
  "אוונגר": "Avenger",
  "אוונסיס": "Avensis",
  "אוליזה": "Ulysse",
  "אומגה": "Omega",
  "אונו": "Uno",
  "אוסטרל": "Austral",
  "אופטימה": "Optima",
  "אופטרה": "Optra",
  "אופירוס": "Opirus",
  "אוקטביה": "Octavia",
  "אורוס": "Urus",
  "אוריס": "Auris",
  "אורלנדו": "Orlando",
  "אטו 3": "Atto 3",
  "אטוס": "Atos",
  "אטלס": "Atlas",
  "אטקה": "Ateca",
  "אטראז'": "Attrage",
  "אי דליברי 7": "e-Deliver 7",
  "אי דליברי 9": "e-Deliver 9",
  "אי-דליוור 3": "e-Deliver 3",
  "אי-דליוור 5": "e-Deliver 5",
  "איביזה": "Ibiza",
  "איגניס": "Ignis",
  "איון HT": "Aion HT",
  "איוניק": "Ioniq",
  "איוניק 5": "Ioniq 5",
  "איוניק 5 N": "Ioniq 5 N",
  "איוניק 6": "Ioniq 6",
  "איוס": "Eos",
  "אייגו": "Aygo",
  "אייגו X": "Aygo X",
  "אייסמן": "Aceman",
  "אימפלה": "Impala",
  "אימפרזה": "Impreza",
  "אינטגרה": "Integra",
  "אינסיגניה": "Insignia",
  "אינסייט": "Insight",
  "אינקה": "Inca",
  "איפון": "Ippon",
  "אכאדיה": "Acadia",
  "אלבאה": "Albea",
  "אלהמברה": "Alhambra",
  "אלטו": "Alto",
  "אלטימה": "Altima",
  "אלמרה": "Almera",
  "אלנטרה": "Elantra",
  "אלנטרה N": "Elantra N",
  "אלרו": "Alero",
  "אלתיאה": "Altea",
  "אמארוק": "Amarok",
  "אמירה": "Emira",
  "אניאק iV": "Enyaq iV",
  "אנקלייב": "Enclave",
  "אסטרה": "Astra",
  "אסטרו": "Astro",
  "אספרו": "Espero",
  "אסקורט": "Escort",
  "אסקייפ": "Escape",
  "אסקלייד": "Escalade",
  "אפ": "Up!",
  "אפיקה": "Epica",
  "אפלאוז": "Applause",
  "אפלנדר": "Uplander",
  "אפסילון": "Ypsilon",
  "אקווינוקס": "Equinox",
  "אקונוליין": "Econoline",
  "אקורד": "Accord",
  "אקטיון": "Actyon",
  "אקליפס": "Eclipse",
  "אקליפס קרוס": "Eclipse Cross",
  "אקס טרייל": "X-Trail",
  "אקסטרה": "Xterra",
  "אקסיום": "Axiom",
  "אקסנט": "Accent",
  "אקסנט i25": "Accent i25",
  "אקספדישן": "Expedition",
  "אקספלורר": "Explorer",
  "אקספרט": "Expert",
  "אקספרס": "Express",
  "ארונה": "Arona",
  "ארטאון": "Arteon",
  "אריה": "Ariya",
  "אריזו 8": "Arrizo 8",
  "ארמדה": "Armada",
  "ארקנה": "Arkana",
  "באיון": "Bayon",
  "בולט EUV": "Bolt EUV",
  "בולט EV": "Bolt EV",
  "בוקס": "Box",
  "בוקסטר": "Boxster",
  "בוקסר": "Boxer",
  "בורה": "Bora",
  "בורן": "Born",
  "ביגסטר": "Bigster",
  "ביפר": "Bipper",
  "בלייזר": "Blazer",
  "בלנו": "Baleno",
  "בנטאיגה": "Bentayga",
  "בראבה": "Brava",
  "בראבו": "Bravo",
  "ברונקו": "Bronco",
  "ברונקו ספורט": "Bronco Sport",
  "ברייטדרופ": "BrightDrop",
  "ברלינגו": "Berlingo",
  "בררה": "Brera",
  "ג'אז": "Jazz",
  "ג'אמפי": "Jumpy",
  "ג'ויס": "Joice",
  "ג'וליה": "Giulia",
  "ג'ולייטה": "Giulietta",
  "ג'וניור": "Junior",
  "ג'וק": "Juke",
  "ג'טה": "Jetta",
  "ג'ימי": "Jimmy",
  "ג'ימני": "Jimny",
  "ג'נסיס": "Genesis",
  "ג'רני": "Journey",
  "גאלאנט": "Galant",
  "גאלופר": "Galloper",
  "גולף": "Golf",
  "גוסט": "Ghost",
  "גטס": "Getz",
  "גיבלי": "Ghibli",
  "גלאקסי": "Galaxy",
  "גלדיאטור": "Gladiator",
  "גלורי 580": "Glory 580",
  "גלקסי E5": "Galaxy E5",
  "גראן-טוריסמו": "GranTurismo",
  "גראן-קבריו": "GranCabrio",
  "גראנד היילנדר": "Grand Highlander",
  "גראנד וואגוניר": "Grand Wagoneer",
  "גראנד וויאג'ר": "Grand Voyager",
  "גרנד ויטרה": "Grand Vitara",
  "גרנד מוב": "Gran Move",
  "גרנד פרי": "Grand Prix",
  "גרנד צ'ירוקי": "Grand Cherokee",
  "גרנדיור": "Grandeur",
  "גרנדיס": "Grandis",
  "גרנדלנד": "Grandland",
  "גרקאלה": "Grecale",
  "ג׳וגר": "Jogger",
  "דאבל יו 5": "W5",
  "דאסטר": "Duster",
  "דדרה": "Dedra",
  "דובלו": "Doblo",
  "דולפין": "Dolphin",
  "דולפין סרף": "Dolphin Surf",
  "דוקאטו": "Ducato",
  "דוקר": "Dokker",
  "דורנגו": "Durango",
  "די-מקס": "D-Max",
  "דיילי": "Daily",
  "דיסקברי": "Discovery",
  "דיסקברי ספורט": "Discovery Sport",
  "דיפנדר": "Defender",
  "דלתא": "Delta",
  "דמיו": "Demio",
  "דרים": "Dream",
  "האמר EV": "Hummer EV",
  "האן": "Han",
  "הובר H6": "Hover H6",
  "הוסדו": "H5",
  "הורקאן": "Huracan",
  "הייאס": "HiAce",
  "היילנדר": "Highlander",
  "היילקס": "Hilux",
  "היילקס ויגו": "Hilux Vigo",
  "ואנטאג'": "Vantage",
  "ואנקוויש": "Vanquish",
  "ואריו": "Vario",
  "וגוניר": "Wagoneer",
  "וואגון R+": "Wagon R+",
  "וויאג'ר": "Voyager",
  "ווינדסטאר": "Windstar",
  "ווינר": "Winner",
  "וול-סאטיס": "Vel Satis",
  "וולט": "Volt",
  "ויאנו": "Viano",
  "ויו": "View",
  "ויואנט/רזו": "Vivant/Rezzo",
  "ויוארו": "Vivaro",
  "ויטו": "Vito",
  "ויטרה": "Vitara",
  "ולוסטר": "Veloster",
  "ונדורה": "Vandura",
  "ונזה": "Venza",
  "ונטו": "Vento",
  "וניו": "Venue",
  "וקטרה": "Vectra",
  "ורסו": "Verso",
  "ורסו-S": "Verso-S",
  "זאפירה": "Zafira",
  "זאפירה לייף": "Zafira Life",
  "זואי": "Zoe",
  "זפיר": "Zephyr",
  "חיפושית": "Beetle",
  "טאהו": "Tahoe",
  "טאון אנד קאנטרי": "Town & Country",
  "טאון קאר": "Town Car",
  "טאורוס": "Taurus",
  "טאיגו": "Taigo",
  "טאנג": "Tang",
  "טאקומה": "Tacoma",
  "טאראקן": "Terracan",
  "טארו": "Taro",
  "טוארג": "Touareg",
  "טווינגו": "Twingo",
  "טווסקאן": "Tavascan",
  "טולדו": "Toledo",
  "טונדרה": "Tundra",
  "טונלה": "Tonale",
  "טוסון": "Tucson",
  "טוראן": "Touran",
  "טורנאו קאסטום": "Tourneo Custom",
  "טורנאו קונקט": "Tourneo Connect",
  "טורס": "Torres",
  "טיאגו 4 פרו": "Tiggo 4 Pro",
  "טיבולי": "Tivoli",
  "טיגו 7 פרו": "Tiggo 7 Pro",
  "טיגו 8 פרו": "Tiggo 8 Pro",
  "טיגו 9": "Tiggo 9",
  "טיגואן": "Tiguan",
  "טיגואן אולספייס": "Tiguan Allspace",
  "טיגרה": "Tigra",
  "טידה": "Tiida",
  "טייקן": "Taycan",
  "טיפו": "Tipo",
  "טיקו": "Tico",
  "טלורייד": "Telluride",
  "טליה/סימבול": "Thalia/Symbol",
  "טלקוליין": "Telcoline",
  "טמפרה": "Tempra",
  "טנדר (בראט)": "Brat",
  "טראוולר": "Traveller",
  "טראוורס": "Traverse",
  "טראנו": "Terrano",
  "טראפיק": "Trafic",
  "טראקו": "Tarraco",
  "טראקס": "Trax",
  "טרג'ט": "Trajet",
  "טרופר": "Trooper",
  "טריביוט": "Tribute",
  "טריבקה": "Tribeca",
  "טריוס": "Terios",
  "טרייטון / L200": "Triton / L200",
  "טרייל בלייזר": "TrailBlazer",
  "טרייסר": "Tracer",
  "טרנזיט": "Transit",
  "טרנזיט קוסטום": "Transit Custom",
  "טרנספורטר": "Transporter",
  "יאריס": "Yaris",
  "יאריס GR": "Yaris GR",
  "יאריס קרוס": "Yaris Cross",
  "יודו 3": "Yudo 3",
  "יוקון": "Yukon",
  "ייטי": "Yeti",
  "כרומה": "Croma",
  "כריזמה": "Carisma",
  "לאון": "Leon",
  "לאונה": "Leone",
  "לאנוס": "Lanos",
  "לארגו": "Largo",
  "לבורג": "Levorg",
  "לבנטה": "Levante",
  "לג'נד": "Legend",
  "לגאסי": "Legacy",
  "לגונה": "Laguna",
  "לגנזה": "Leganza",
  "לה-סייבר": "LeSabre",
  "לה-קרוס": "LaCrosse",
  "לוגאן": "Logan",
  "לוגיסטאר 100": "Logistar 100",
  "לוגיסטאר 200": "Logistar 200",
  "לודג'י": "Lodgy",
  "לומינה מיניוואן": "Lumina APV",
  "לוצרן": "Lucerne",
  "לטיטוד": "Latitude",
  "ליאנה": "Liana",
  "לידו": "Lido",
  "לינאה": "Linea",
  "ליף": "Leaf",
  "לנד קרוזר": "Land Cruiser",
  "לנטרה": "Lantra",
  "לנסר": "Lancer",
  "לנסר איוולושן": "Lancer Evolution",
  "מאבריק": "Maverick",
  "מאטיס": "Matiz",
  "מאטריה": "Materia",
  "מאליבו": "Malibu",
  "מאסטר": "Master",
  "מאסיף": "Massif",
  "מארוול R": "Marvel R",
  "מג'נטיס": "Magentis",
  "מגאן": "Megane",
  "מגאן E-Tech": "Megane E-Tech",
  "מובאנו": "Movano",
  "מודל 3": "Model 3",
  "מודל S": "Model S",
  "מודל X": "Model X",
  "מודל Y": "Model Y",
  "מולטיוואן": "Multivan",
  "מולטיפלה": "Multipla",
  "מונדאו": "Mondeo",
  "מונטה קרלו": "Monte Carlo",
  "מונטרו ספורט": "Montero Sport",
  "מוסו": "Musso",
  "מוסטנג": "Mustang",
  "מוסטנג Mach-E": "Mustang Mach-E",
  "מוקה": "Mokka",
  "מוראנו": "Murano",
  "מטרו": "Metro",
  "מטריס": "Metris",
  "מטריקס": "Matrix",
  "מיטו": "MiTo",
  "מיפה 7": "Mifa 7",
  "מיפה 9": "Mifa 9",
  "מיקרה": "Micra",
  "מנטור/ספיה": "Mentor/Sephia",
  "מקאן": "Macan",
  "מקסימה": "Maxima",
  "מריאה": "Marea",
  "מריבה": "Meriva",
  "נאון": "Neon",
  "נבארה": "Navara",
  "נביגטור": "Navigator",
  "נובירה": "Nubira",
  "נוט": "Note",
  "ניבה": "Niva",
  "ניטרו": "Nitro",
  "נירו": "Niro",
  "נירו פלוס": "Niro Plus",
  "נקסייה": "Nexia",
  "סאברבן": "Suburban",
  "סברינג": "Sebring",
  "סדיצ'י": "Sedici",
  "סדרה 1": "1 Series",
  "סדרה 2": "2 Series",
  "סדרה 3": "3 Series",
  "סדרה 4": "4 Series",
  "סדרה 5": "5 Series",
  "סדרה 6": "6 Series",
  "סדרה 7": "7 Series",
  "סדרה 8": "8 Series",
  "סוברבן": "Suburban",
  "סוואנה": "Savana",
  "סוויל": "Seville",
  "סוויפט": "Swift",
  "סול": "Soul",
  "סולטרה": "Solterra",
  "סולסטיס": "Solstice",
  "סומו": "Sumo",
  "סונומה": "Sonoma",
  "סונטה": "Sonata",
  "סוניק": "Sonic",
  "סופה": "Storm",
  "סופר וואן": "Super Van",
  "סופר לנסר": "Super Lancer",
  "סופר סלון": "Super Saloon",
  "סופרב": "Superb",
  "סופרה": "Supra",
  "סורנטו": "Sorento",
  "סטאריה": "Staria",
  "סטארלט": "Starlet",
  "סטוניק": "Stonic",
  "סטיד": "Steed",
  "סטינגר": "Stinger",
  "סטלביו": "Stelvio",
  "סטרטוס": "Stratus",
  "סי ליאון 07": "Sea Lion 07",
  "סיד": "Ceed",
  "סיוויק": "Civic",
  "סיוויק Type R": "Civic Type R",
  "סיטאן": "Citan",
  "סיטי": "City",
  "סיטי ספיריט": "City Spirit",
  "סיטיגו": "Citigo",
  "סייבטראק": "Cybertruck",
  "סיינה": "Sienna",
  "סיירה": "Sierra",
  "סיירה EV": "Sierra EV",
  "סיל": "Seal",
  "סיל 5": "Seal 5",
  "סיל U": "Seal U",
  "סילברדו": "Silverado",
  "סילברדו EV": "Silverado EV",
  "סיריון": "Sirion",
  "סלטוס": "Seltos",
  "סליקה": "Celica",
  "סלריו": "Celerio",
  "סמוראי": "Samurai",
  "סמרה": "Samara",
  "סנדרו": "Sandero",
  "סנדרו Stepway": "Sandero Stepway",
  "סנטה פה": "Santa Fe",
  "סנטרה": "Sentra",
  "סניק": "Scenic",
  "ספארי": "Safari",
  "ספארק": "Spark",
  "ספורטז'": "Sportage",
  "ספיה": "Sephia",
  "ספיידר": "Spider",
  "ספייס גיר": "Space Gear",
  "ספייס וואגן": "Space Wagon",
  "ספייס סטאר": "Space Star",
  "ספייס ראנר": "Space Runner",
  "ספלאש": "Splash",
  "ספקטר": "Spectre",
  "ספרינג": "Spring",
  "ספרינטר": "Sprinter",
  "ספרן": "Safrane",
  "סקאלה": "Scala",
  "סקודו": "Scudo",
  "סקויה": "Sequoia",
  "סקסו": "Saxo",
  "סראטו": "Cerato",
  "סרטוגה": "Saratoga",
  "סרנה": "Serena",
  "פאביה": "Fabia",
  "פאנאמרה": "Panamera",
  "פאסאט": "Passat",
  "פאסאט CC": "Passat CC",
  "פארק אבניו": "Park Avenue",
  "פאת'פיינדר": "Pathfinder",
  "פג'רו": "Pajero",
  "פולבק": "Fullback",
  "פולו": "Polo",
  "פולסר": "Pulsar",
  "פומה": "Puma",
  "פונטו": "Punto",
  "פונטו איבו": "Punto Evo",
  "פוני": "Pony",
  "פוקוס": "Focus",
  "פור-ראנר": "4Runner",
  "פורוסאנגווה": "Purosangue",
  "פורטה": "Forte",
  "פורטו": "Fortwo",
  "פורטופינו": "Portofino",
  "פורטר": "Porter",
  "פורמנטור": "Formentor",
  "פורסטר": "Forester",
  "פורפור": "Forfour",
  "פטרול": "Patrol",
  "פטריוט": "Patriot",
  "פיאסטה": "Fiesta",
  "פיוז'ן": "Fusion",
  "פיורינו": "Fiorino",
  "פייטון": "Phaeton",
  "פיילוט": "Pilot",
  "פייסמן": "Paceman",
  "פיקנטו": "Picanto",
  "פלואנס": "Fluence",
  "פלוריד": "Florid",
  "פליו": "Palio",
  "פליטווד": "Fleetwood",
  "פליינג ספור": "Flying Spur",
  "פליסדה": "Palisade",
  "פליסיה": "Felicia",
  "פנדה": "Panda",
  "פסיפיקה": "Pacifica",
  "פרג'יו": "Pregio",
  "פרואייס": "Proace",
  "פרואייס סיטי": "Proace City",
  "פרוזה": "Feroza",
  "פרונטרה": "Frontera",
  "פרטנר": "Partner",
  "פרי": "Free",
  "פריוויה": "Previa",
  "פריוס": "Prius",
  "פריוס פלוס": "Prius+",
  "פרייד": "Pride",
  "פריידי": "Friday",
  "פרילנדר": "Freelander",
  "פרימרה": "Primera",
  "פרינס": "Prince",
  "פרלוד": "Prelude",
  "פרמסי": "Premacy",
  "צ'ארג'ר": "Charger",
  "צ'ירוקי": "Cherokee",
  "צ'לנג'ר": "Challenger",
  "צ'רמן": "Chairman",
  "קאדי": "Caddy",
  "קאיימן": "Cayman",
  "קאיין": "Cayenne",
  "קאליבר": "Caliber",
  "קאלינן": "Cullinan",
  "קאמארו": "Camaro",
  "קאמיק": "Kamiq",
  "קאמרי": "Camry",
  "קאנטר": "Canter",
  "קאנטרימן": "Countryman",
  "קאפה": "Kappa",
  "קארוק": "Karoq",
  "קארי": "Carry",
  "קארנס": "Carens",
  "קבסטאר": "Cabstar",
  "קדגא'ר": "Kadjar",
  "קדנזה": "Cadenza",
  "קובו": "Qubo",
  "קוגה": "Kuga",
  "קודיאק": "Kodiaq",
  "קוואטרופורטה": "Quattroporte",
  "קוואליר": "Cavalier",
  "קולבר": "Coolbear",
  "קולורדו": "Colorado",
  "קולט": "Colt",
  "קוליאוס": "Koleos",
  "קומבו": "Combo",
  "קומי": "Komi",
  "קומנדר": "Commander",
  "קומפאס": "Compass",
  "קונה": "Kona",
  "קונטיננטל": "Continental",
  "קונטיננטל GT": "Continental GT",
  "קופה": "Coupe",
  "קופי 01": "Coffee 01",
  "קופי 02": "Coffee 02",
  "קופר": "Cooper",
  "קופר SE (חשמלית)": "Cooper SE",
  "קופר קבריולט": "Cooper Cabrio",
  "קוראז": "Courage",
  "קורבט": "Corvette",
  "קורדובה": "Cordoba",
  "קורה": "Cuore",
  "קורולה": "Corolla",
  "קורולה ורסו": "Corolla Verso",
  "קורולה קרוס": "Corolla Cross",
  "קורנדו": "Korando",
  "קורסה": "Corsa",
  "קורסיקה": "Corsica",
  "קיירון": "Kyron",
  "קלאבמן": "Clubman",
  "קלארוס": "Clarus",
  "קליאו": "Clio",
  "קליפורניה": "California",
  "קלריטי": "Clarity",
  "קנגו": "Kangoo",
  "קסדוס 6": "Xedos 6",
  "קסדוס 9": "Xedos 9",
  "קסנטיה": "Xantia",
  "קסקדה": "Cascada",
  "קסרה": "Xsara",
  "קפטיבה": "Captiva",
  "קפצ'ור": "Captur",
  "קראוול": "Caravelle",
  "קראוון": "Caravan",
  "קראון": "Crown",
  "קראפטר": "Crafter",
  "קרוז": "Cruze",
  "קרוסאובר": "Crossover",
  "קרוסטרק": "Crosstrek",
  "קרוסלנד": "Crossland",
  "קרוסלנד X": "Crossland X",
  "קרוספייר": "Crossfire",
  "קרינה": "Carina",
  "קרניבל": "Carnival",
  "קשקאי": "Qashqai",
  "ראפיד": "Rapid",
  "רודאו": "Rodeo",
  "רודיוס": "Rodius",
  "רודסטר": "Roadster",
  "רוולטו": "Revuelto",
  "רומא": "Roma",
  "רומסטר": "Roomster",
  "ריו": "Rio",
  "ריינג' רובר": "Range Rover",
  "ריינג' רובר איווק": "Range Rover Evoque",
  "ריינג' רובר ולאר": "Range Rover Velar",
  "ריינג' רובר ספורט": "Range Rover Sport",
  "ריינג'ר": "Ranger",
  "רייסר": "Racer",
  "ריפטר": "Rifter",
  "רנגייד": "Renegade",
  "רנגלר": "Wrangler",
  "רנדוו": "Rendezvous",
  "רקסטון": "Rexton",
  "שאטל": "Shuttle",
  "שומה": "Shuma",
  "שירוקו": "Scirocco",
  "שרייד": "Charade",
}
