services:
  - type: web
    name: carinfo-bot
    runtime: docker
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        value: "594206475"
      - key: WEBAPP_URL
        value: "https://carinfo-bot.onrender.com"
      - key: PAYPAL_ME
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
    healthCheckPath: /health
