services:
  - type: web
    name: carinfo-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        value: "594206475"
      - key: GITHUB_PAT
        value: "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"
      - key: GITHUB_REPO
        value: "Gal9amar/carinfo-bot"
      - key: GITHUB_DATA_PATH
        value: "data/users.json"
      - key: GITHUB_BRANCH
        value: "main"
    healthCheckPath: /
